# Generated by Django 3.0.4 on 2020-04-07 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_user_daily_posts', models.IntegerField(default=20)),
                ('registered_user_feedback_limit', models.IntegerField(default=10)),
                ('unregistered_user_daily_posts', models.IntegerField(default=0)),
                ('unregistered_user_feedback_limit', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField(max_length=512)),
                ('answer', models.TextField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Answered', 'Answered'), ('Deleted by user', 'Deleted By User'), ('Ignored', 'Ignored')], default='Pending', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
